language: rust

rust:
  - nightly

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo build --verbose --no-default-features
  - cargo test --verbose --no-default-features
  - cargo build --verbose --no-default-features --features "heap"
  - cargo test --verbose --no-default-features --features "heap"