language: rust

rust:
  - 1.28
  - nightly

script:
  - cargo test --verbose
  - cargo test --verbose --no-default-features
  - cargo test --verbose --features "coerce"
  - cargo test --verbose --no-default-features --features "coerce"