language: rust

rust:
  - nightly

script:
  - cargo test --verbose
  - cargo test --verbose --features "unsize"
  - cargo test --verbose --no-default-features --features "heap"
  - cargo test --verbose --no-default-features --features "unsize"
  - cargo test --verbose --no-default-features --features "heap unsize"