language: rust

os:
  - linux
  - osx
  - windows

matrix:
  include:
    - rust: 1.28
      script:
        - cargo test --verbose
    - rust: nighlty
      script:
      - cargo test --verbose
      - cargo test --verbose --no-default-features
      - cargo test --verbose --features "coerce"
      - cargo test --verbose --no-default-features --features "coerce"
      