language: rust

os:
  - linux
  - osx
  - windows

rust: 
  - 1.28.0
  - nightly
    env: NIGHTLY=1

script:
- 'cargo test --verbose'
- '["$NIGHTLY" = "1"] && cargo test --verbose --no-default-features'
- '["$NIGHTLY" = "1"] && cargo test --verbose --features "coerce"'
- '["$NIGHTLY" = "1"] && cargo test --verbose --no-default-features --features "coerce"'
