[package]
name = "smallbox"
version = "0.2.1"
authors = ["goandylok"]
description = "Box dynamically-sized types on stack"
repository = "https://github.com/goandylok/smallbox"
documentation = "https://docs.rs/smallbox/"
keywords = ["box", "alloc", "dst", "stack", "no_std"]
license = "MIT"